import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST(req: Request) {
  const body = await req.json();
  const { action, binId, transactionId, plastic, cans, secret } = body;

  // 1. Verify Secret (Add PI_SECRET to your .env.local file in Next.js)
  if (secret !== process.env.PI_SECRET) {
    return NextResponse.json({ error: "Unauthorized Machine" }, { status: 401 });
  }

  // --- START ACTION ---
  if (action === "START") {
    // Create a new transaction
    const newTx = await prisma.recycleTransaction.create({
      data: {
        binId,
        status: "ACTIVE",
        // claimSecret is auto-generated by Prisma @default(cuid())
      }
    });

    return NextResponse.json({ 
      success: true, 
      transactionId: newTx.id,
      claimSecret: newTx.claimSecret 
    });
  }

  // --- STOP ACTION ---
  if (action === "STOP" && transactionId) {
    // Save the final counts
    await prisma.recycleTransaction.update({
      where: { id: transactionId },
      data: {
        plastic: plastic || 0,
        cans: cans || 0,
        status: "COMPLETED"
      }
    });

    return NextResponse.json({ success: true });
  }

  return NextResponse.json({ error: "Invalid Action" }, { status: 400 });
}